module.exports = {
  "currency": {
    "name": "USD",
    "symbol": "$",
    "countryCode": "US",
    "currencyCode": "$",
    "isDefault": true
  },
  "_id": "67d7e9f0ccd4e02f7ee3dba3",
  "privacyPolicyLink": "<h4>Privacy Policy for Figgy</h4><h4><br></h4><h5>How We Use Your Information</h5><h6>Personal Information:</h6><p><span style=\"color: rgb(187, 187, 187);\">We use your email address for account management and to communicate with you about updates or important information. </span></p><h6>Usage Data:</h6><p><span style=\"color: rgb(187, 187, 187); font-family: Helvetica, Arial, sans-serif; font-size: 13px; font-weight: 400;\">We analyze usage patterns to improve our app's content and user experience. </span></p><h6>Device Information:</h6><p><span style=\"color: rgb(187, 187, 187);\">We use device information for technical purposes, such as troubleshooting and ensuring compatibility.</span></p><h6>Information Sharing</h6><p><span style=\"color: rgb(187, 187, 187);\">We do not sell, trade, or otherwise transfer your personally identifiable information to third parties. We may share aggregated and anonymized data for statistical purposes.</span></p><h6>Security</h6><p><span style=\"color: rgb(187, 187, 187);\">We take reasonable measures to protect your personal information from unauthorized access or disclosure. However, no method of transmission over the Internet or electronic storage is completely secure. </span></p><h6>Your Choices</h6><p><span style=\"color: rgb(187, 187, 187);\">You can manage your account settings and preferences within the app. You may opt out of promotional emails at any time by following the unsubscribe instructions in the email. </span></p><h6>Changes to This Privacy Policy</h6><p><span style=\"color: rgb(187, 187, 187);\">We may update this Privacy Policy from time to time. Any changes will be posted on this page, and the \"Last Updated\" date will be revised accordingly. </span></p><h6>Contact Us</h6><ol><li><span style=\"color: rgb(187, 187, 187);\">If you have any questions or concerns about this Privacy Policy, please contact us at [your contact email]. By using Wallki, you agree to the terms outlined in this Privacy Policy.</span></li></ol>",
  "termsOfUsePolicyLink": "<h4>Terms and Condition for Figgy</h4><h4><br></h4><h5>How We Use Your Information</h5><h6>Personal Information:</h6><p><span style=\"color: rgb(187, 187, 187);\">We use your email address for account management and to communicate with you about updates or important information. </span></p><h6>Usage Data:</h6><p><span style=\"color: rgb(187, 187, 187);\">We analyze usage patterns to improve our app's content and user experience. </span></p><h6>Device Information:</h6><p><span style=\"color: rgb(187, 187, 187);\">We use device information for technical purposes, such as troubleshooting and ensuring compatibility.</span></p><h6>Information Sharing</h6><p><span style=\"color: rgb(187, 187, 187);\">We do not sell, trade, or otherwise transfer your personally identifiable information to third parties. We may share aggregated and anonymized data for statistical purposes.</span></p><h6>Security</h6><p><span style=\"color: rgb(187, 187, 187);\">We take reasonable measures to protect your personal information from unauthorized access or disclosure. However, no method of transmission over the Internet or electronic storage is completely secure. </span></p><h6>Your Choices</h6><p><span style=\"color: rgb(187, 187, 187);\">You can manage your account settings and preferences within the app. You may opt out of promotional emails at any time by following the unsubscribe instructions in the email. </span></p><h6>Contact Us</h6><ol><li><span style=\"color: rgb(187, 187, 187);\">If you have any questions or concerns about this Privacy Policy, please contact us at [your contact email]. By using Wallki, you agree to the terms outlined in this Privacy Policy.</span></li></ol><p><br></p>",
  "googlePlayEnabled": false,
  "stripeEnabled": true,
  "stripePublishableKey": "pk_test_51PnZpxCgbHHJtm7RPVLjX28kr3mQGhHobJ1WaCGKBNh9cWZKLJJdu5f1EltNyjNVzcdQSYgJfizsbbC2RP987rTE00pdwG8KyZ",
  "stripeSecretKey": "REDACTED_STRIPE_SECRET",
  "razorpayEnabled": true,
  "razorpayId": "RAZOR PAY ID",
  "razorpaySecretKey": "rzp_test_SjZz9HC7RGCfCb",
  "flutterwaveEnabled": true,
  "flutterwaveId": "FLWPUBK_TEST-cdc51a4df113a91fe33a914eaf8d1c75-X",
  "loginBonus": 5500,
  "isDemoData": true,
  "minCoinsToConvert": 1000,
  "minCoinsForUserPayout": 1,
  "minCoinsForHostPayout": 100,
  "minCoinsForAgencyPayout": 10,
  "maxFreeChatMessages": 1,
  "privateKey": {},
  "createdAt": "2025-03-17T09:22:56.775Z",
  "updatedAt": "2025-06-20T09:28:01.028Z",
  "adminCommissionRate": 10,
  "agoraAppCertificate": "e8fe12c2e67042b4a3d503f8cd0475d0",
  "agoraAppId": "351b3aecd6544324aae28ea1e3a6ff3c",
  "audioPrivateCallRate": 35,
  "chatInteractionRate": 15,
  "femaleRandomCallRate": 25,
  "generalRandomCallRate": 35,
  "isAppEnabled": false,
  "maleRandomCallRate": 15,
  "videoPrivateCallRate": 45,
  "callInitiatedAt": 10,
  "messageInitiatedAt": 10
};