module.exports = {
  "currency": {
    "name": "Bitcoin",
    "symbol": "BTC",
    "countryCode": "US",
    "currencyCode": "USD",
    "isDefault": true
  },
  "_id": "67d7e9f0ccd4e02f7ee3dba3",
  "privacyPolicyLink": "PRIVACY POLICY LINK",
  "termsOfUsePolicyLink": "TERMS OF USE POLICY LINK",
  "googlePlayEnabled": false,
  "stripeEnabled": false,
  "stripePublishableKey": "STRIPE PUBLISHABLE KEY",
  "stripeSecretKey": "STRIPE SECRET KEY",
  "razorpayEnabled": true,
  "razorpayId": "RAZOR PAY ID",
  "razorpaySecretKey": "RAZOR SECRET KEY",
  "flutterwaveEnabled": true,
  "flutterwaveId": "FLUTTER WAVE ID",
  "loginBonus": 5000,
  "isDemoData": true,
  "minCoinsToConvert": 1000,
  "minCoinsForUserPayout": 1,
  "minCoinsForHostPayout": 100,
  "minCoinsForAgencyPayout": 10,
  "maxFreeChatMessages": 1,
  "privateKey": {},
  "createdAt": "2025-03-17T09:22:56.775Z",
  "updatedAt": "2025-04-18T13:33:13.244Z",
  "adminCommissionRate": 1,
  "agoraAppCertificate": "85576174fc0b469d84f00c9e4875edcb",
  "agoraAppId": "f3f9337c8da0404ba8f9cb1c5549c024",
  "audioPrivateCallRate": 15,
  "chatInteractionRate": 5,
  "femaleRandomCallRate": 0,
  "generalRandomCallRate": 15,
  "isAppEnabled": false,
  "maleRandomCallRate": 15,
  "videoPrivateCallRate": 25
};