module.exports = {
  "_id": "67d7e9f0ccd4e02f7ee3dba3",
  "currency": {
    "name": "Bitcoin",
    "symbol": "BTC",
    "countryCode": "US",
    "currencyCode": "USD",
    "isDefault": true
  },
  "privacyPolicyLink": "<h2>Add Privacy Policy </h2><h2><br></h2><ul><li>dfjdgoifjitrytytryio</li></ul><ol><li>grtytyttyty</li><li>2dsssds</li><li><strong>dsdsdsdsds</strong></li></ol>",
  "termsOfUsePolicyLink": "TERMS OF USE POLICY LINK",
  "googlePlayEnabled": false,
  "stripeEnabled": false,
  "stripePublishableKey": "STRIPE PUBLISHABLE KEY",
  "stripeSecretKey": "STRIPE SECRET KEY",
  "razorpayEnabled": true,
  "razorpayId": "RAZOR PAY ID",
  "razorpaySecretKey": "RAZOR SECRET KEY",
  "flutterwaveEnabled": true,
  "flutterwaveId": "FLUTTER WAVE ID",
  "loginBonus": 5000,
  "isDemoData": true,
  "minCoinsToConvert": 1000,
  "minCoinsForUserPayout": 1,
  "minCoinsForHostPayout": 100,
  "minCoinsForAgencyPayout": 10,
  "maxFreeChatMessages": 1,
  "privateKey": {},
  "adminCommissionRate": 1,
  "agoraAppCertificate": "85576174fc0b469d84f00c9e4875edcb",
  "agoraAppId": "f3f9337c8da0404ba8f9cb1c5549c024",
  "audioPrivateCallRate": 15,
  "chatInteractionRate": 5,
  "femaleRandomCallRate": 0,
  "generalRandomCallRate": 15,
  "isAppEnabled": false,
  "maleRandomCallRate": 15,
  "videoPrivateCallRate": 25,
  "createdAt": "2025-03-17T09:22:56.775Z",
  "updatedAt": "2025-04-21T08:48:18.937Z"
};